import { LineEdit } from "std-widgets.slint";
import { Styles } from "../styles/styles.slint";
import { botonPrincipal } from "../components/boton-prinicipal.slint";
import { inputRegistro } from "../components/input-registro.slint";

export component login inherits Rectangle {
    
    callback go_to_register;
    
    callback go_to_rooms;

    callback login();

    in-out property <string> email: "";
    in-out property <string> pswd: "";

    in-out property <string> empty_error: "";
    in-out property <color> empty_error_text_color: #ff0000;
    in-out property <color> input_border_color: #e8e8e8;

    background: white;

    GridLayout {
        padding: 45px;

        Row {
            Text {
                text: "Faena";
                font-size: 80px;
                height: 95px;
                font-weight: Styles.bold;
                vertical-alignment: center;
                horizontal-alignment: center;
                wrap: word-wrap;
                color: Styles.azul-fuerte;
            }
        }
        Row {
            Image {
                source: @image-url("../img/FAENApng.png");
                height: 180px;
            }
        }
        Row {
            Text {
                text: "Registrate o inicia sesión en la app para unirte a la Faenation";
                font-size: 17px;
                height: 52px;
                font-weight: Styles.semibold;
                vertical-alignment: center;
                horizontal-alignment: center;
                wrap: word-wrap;
                color: Styles.azul-bajo;
            }
        }

        Row {
            VerticalLayout {
                spacing: 2px;
                padding-top: 18px;

                //Iniciar Sesión (Correo Electrónico)
                inputRegistro {
                    texto <=> root.email;
                    placeholder: "Correo electronico";
                    tipo: text;
                }

                //Iniciar Sesión (Contraseña)
                inputRegistro {
                    texto <=> root.pswd;
                    placeholder: "Contraseña";
                    tipo: password;
                }
            }
        }

        Row {
            VerticalLayout {
                spacing: 10px;
                
                //Errores
                Rectangle {
                    height: 13px;
                    background: transparent;

                    Text {
                        text: root.empty_error;
                        color: root.empty_error_text_color;
                        horizontal-alignment: center;
                        font-size: 14px;
                        font-weight: Styles.semibold;
                        width: parent.width;
                    }
                }

                //Botón Iniciar Sesión
                HorizontalLayout {
                    alignment: center;

                    botonPrincipal {
                        texto: "Iniciar sesión";

                        click => {
                            root.login();
                            root.go_to_rooms();
                        }
                    }
                }
            }
        }

        Row {

            //Link a registro
            VerticalLayout {
                spacing: 0px;
                padding-top: 15px;

                Text {
                    text: "¿Aún no tienes cuenta?";
                    height: 19px;
                    font-size: 14px;
                    color: Styles.negro;
                    font-weight: Styles.semibold;
                    horizontal-alignment: left;
                }

                TouchArea {
                    height: 18px;

                    clicked => { 
                        root.go_to_register(); 
                    }

                    Text {
                        width: parent.width;
                        height: 19px;
                        text: "Crear una cuenta";
                        font-size: 14px;
                        font-weight: Styles.semibold;
                        color: Styles.azul-verde;
                        horizontal-alignment: left;        
                    }
                }
            }
        }
    }
}