import { welcomeFaena } from "welcome.slint";
import { login } from "login.slint";
import { register } from "register.slint";
import { Navbar } from "../components/navbar.slint";
import { startMenu } from "startMenu.slint";
import { visualizeRoomMember } from "visualizeRoomMember.slint";
import { Styles } from "../Styles/styles.slint";

export component MainWindow inherits Window {
    
    title: "Autenticación";

    property <bool> welcome: true;
    property <bool> is_login: false;
    property <bool> is_register: false;

    property <bool> is_startMenu: false;
    property <bool> is_visualizeRoomMember: false;

    //login
    in-out property <string> email: "";
    in-out property <string> pswd: "";
    in-out property <string> empty_error: "";
    in-out property <color> empty_error_text_color: Styles.empty_error_text_color;
    in-out property <color> input_border_color: Styles.input_border_color;
    
    out property <color> rojo: Styles.empty_error_text_color;
    out property <color> verde: Styles.verde;
    out property <color> border: Styles.input_border_color;

    // Callback del login
    callback login();

    welcomeFaena {
        visible: root.welcome;

        go_to_login => {
            root.welcome = false;
            root.is_login = true;
        }
    }

    login_page:=login {
        visible: root.is_login;

        //bindings
        email <=> root.email;
        pswd <=> root.pswd;
        empty_error <=> root.empty_error;
        empty_error_text_color <=> root.empty_error_text_color;
        input_border_color <=> root.input_border_color;

        go_to_register => {
            root.is_login = false;
            root.is_register = true;
        }

        login =>{
            root.login();
        }

        go_to_startMenu => {
            root.is_login = false;
            root.is_startMenu = true;
        }
        
    }

    startMenu {
        visible: root.is_startMenu;

        go_to_visualizeRoomMember => {
            root.is_startMenu = false;
            root.is_visualizeRoomMember = true;
        }
    }

    visualizeRoomMember {
        visible: root.is_visualizeRoomMember;
    }

    register {
        visible: root.is_register;

        go_to_login => {
            root.is_register = false;
            root.is_login = true;
        }
    }
}