import { welcomeFaena } from "welcome.slint";
import { login } from "login.slint";
import { register } from "register.slint";
import { Navbar } from "../components/navbar.slint";
import { startMenu } from "startMenu.slint";
import { visualizeRoomMember } from "visualizeRoomMember.slint";
import { visualizeRoomAdmin } from "visualizeRoomAdmin.slint";
import { createRoom } from "createRoom.slint";
import { Styles } from "../Styles/styles.slint";
import "../Styles/fonts/SourceSansPro-Regular.otf";
import { LineEdit } from "std-widgets.slint";
import { foco-invisible } from "../components/foco-invisible.slint";

import { inputRegistro } from "../components/input-registro.slint";

export component MainWindow inherits Window {
    
    title: "Autenticación";
    in-out property <int> pantalla_actual: 0;
 
    //Indice que se comunica con el índice de la Navbar
    in-out property <int> navbarIndex: 1;

    //login
    in-out property <string> email_login: "";
    in-out property <string> pswd_login: "";
    in-out property <string> empty_error: "";
    in-out property <color> empty_error_text_color: Styles.empty_error_text_color;
    in-out property <color> input_border_color: Styles.input_border_color;
    
    out property <color> rojo: Styles.empty_error_text_color;
    out property <color> verde: Styles.verde;
    out property <color> border: Styles.input_border_color;

    //registro
    in-out property <string> username: "";
    in-out property <string> email_registro: "";
    in-out property <string> pswd_registro: "";
    in-out property <string> confirm_pswd: "";

    // Callbacks de conexion con rust
    callback login();
    callback registrar();

    //fuente para todos los texto de main.slint
    default-font-family: "Source Sans Pro";

    FocoInvisible:=foco-invisible{} //LineText para evitar que se quede el marcador cuando se cambia de pantalla

    if(pantalla_actual==0):welcomeFaena { //    0-INICIO

        go_to_login => {
            root.pantalla_actual=1;
        }
    }

    if(pantalla_actual==1):login { //   1-LOGIN

        //bindings
        email <=> root.email_login;
        pswd <=> root.pswd_login;
        empty_error <=> root.empty_error;
        empty_error_text_color <=> root.empty_error_text_color;
        input_border_color <=> root.input_border_color;

        go_to_register => { //boton para ir a registrarse
            root.pantalla_actual=2;
            FocoInvisible.clear-focus();
            FocoInvisible.clear-selection();
            root.email_login="";
            root.pswd_login="";
            root.empty_error="";
        }

        login =>{ //boton de login, dependiendo el caso, el backend va a cambiar el flujo del ui
            root.login();
        }        
    }

    if(pantalla_actual==2):register { //    2-REGISTRO
        
        //bindings
        username <=> root.username;
        email <=> root.email_registro;
        pswd <=> root.pswd_registro;
        confirm_pswd <=> root.confirm_pswd;
        empty_error <=> root.empty_error;
        empty_error_text_color <=> root.empty_error_text_color;
        input_border_color <=> root.input_border_color;

        go_to_login => {
            root.pantalla_actual=1;
            FocoInvisible.clear-focus();
            FocoInvisible.clear-selection();
            root.username="";
            root.email_registro="";
            root.pswd_registro="";
            root.confirm_pswd="";
            root.empty_error="";
        }
        registrar => {
            root.registrar();
        }
    }

    if(pantalla_actual==3):startMenu { //   3-MENU DE INICIO
        navbarIndex <=> root.navbarIndex;

        go_to_visualizeRoomAdmin => {
            root.pantalla_actual=5;
            root.navbarIndex = 1;
        }

        go_to_visualizeRoomMember => {
            root.pantalla_actual=4;
            root.navbarIndex = 1;
        }

        go_to_createRoom => {
            root.pantalla_actual=6;
            root.navbarIndex = 2;
        }
    }

    if(pantalla_actual==4): visualizeRoomMember { //    4-VER SALA
        navbarIndex <=> root.navbarIndex;

        go_to_rooms => {
            root.pantalla_actual=3;
            root.navbarIndex = 1;
        }

        go_to_createRoom => {
            root.pantalla_actual=6;
            root.navbarIndex = 2;
        }
    }

    if(pantalla_actual==5): visualizeRoomAdmin { //     5=VER SALA COMO ADMIN
        navbarIndex <=> root.navbarIndex;

        go_to_rooms => {
            root.pantalla_actual=3;
            root.navbarIndex = 1;
        }

        go_to_createRoom => {
            root.pantalla_actual=6;
            root.navbarIndex = 2;
        }
    }

    if(pantalla_actual==6):createRoom { //  6-CREAR SALAS
        navbarIndex <=> root.navbarIndex;

        go_to_rooms => {
            root.pantalla_actual=3;
            root.navbarIndex = 1;
        }
    }
}