import { LineEdit, HorizontalBox } from "std-widgets.slint";
import { Styles } from "../styles/styles.slint";

export component inputRegistro {
    in-out property <string> texto:"";
    in property <string> placeholder;
    in property <InputType> tipo;

    GridLayout {
        spacing: 10px;
        
        Row {
            LineEdit {
                text <=> root.texto;
                width: 100%;
                height: 40px;
                font-size: 16px;
                horizontal-alignment: center;
                placeholder-text: root.placeholder;
                input-type: tipo;
            }
        }
    }
}