import { Styles } from "../styles/styles.slint";

export component Navbar inherits Rectangle {
    //width: parent.width;
    height: 64px;
    background: Styles.azul-bajo;

    callback go_to_history;
    callback go_to_rooms;
    callback go_to_createRoom;

    in-out property <int> indiceAzulFuerte: 1;

    Rectangle {
        width: parent.width / 6;
        height: parent.height / 2.2;
        y: 8px;
        x: (parent.width / 3) * root.indiceAzulFuerte + (parent.width / 3 - parent.width / 6) / 2;
        border-radius: 16px;
        background: Styles.azul-fuerte;
    }

    HorizontalLayout {
        //width: parent.width;
        //height: parent.height;

        Rectangle {
            //width: parent.width / 3;
            height: parent.height;

            TouchArea {
                width: parent.width;
                height: parent.height;
                clicked => {
                    root.indiceAzulFuerte = 0;
                    root.go_to_history();
                }
            }

            Image {
                source: @image-url("../img/folder.png");
                y: 10px;
            }

            Text {
                text: "Historial";
                color: white;
                vertical-alignment: bottom;
                horizontal-alignment: center;
                font-size: 16px;
                font-weight: 600;
                width: parent.width;
                y: 38px;
            }
        }

        Rectangle {
            //width: parent.width / 3;
            height: parent.height;

            TouchArea {
                width: parent.width;
                height: parent.height;
                clicked => {
                    root.indiceAzulFuerte = 1;
                    root.go_to_rooms();
                    debug("En Ver Salas");
                }
            }

            Image {
                source: @image-url("../img/list.png");
                y: 10px;
            }

            Text {
                text: "Ver Salas";
                color: white;
                vertical-alignment: bottom;
                horizontal-alignment: center;
                font-size: 16px;
                font-weight: 600;
                width: parent.width;
                y: 38px;
            }
        }

        Rectangle {
            //width: parent.width / 3;
            height: parent.height;

            TouchArea {
                width: parent.width;
                height: parent.height;
                clicked => {
                    root.indiceAzulFuerte = 2;
                    root.go_to_createRoom();
                    debug("En Crear Sala");
                }
            }

            Image {
                source: @image-url("../img/add_circle.png");
                y: 10px;
            }

            Text {
                text: "Crear Sala";
                color: white;
                vertical-alignment: bottom;
                horizontal-alignment: center;
                font-size: 16px;
                font-weight: 600;
                width: parent.width;
                y: 38px;
            }
        }
    }
}